# -*- coding: utf-8 -*-
"""tei-data-extraction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8iruhr_OTAsEVb6bmCqCss9Ui26rAXF
"""

import requests
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Specify the target folder path in your Google Drive
target_folder = '/content/drive/MyDrive/TEI_files/'

# Create the target folder if it doesn't exist
os.makedirs(target_folder, exist_ok=True)

# Iterate over the range of TEI numbers (1-2352)
for tei_number in range(1, 2353):
    # Create the URL for the TEI file
    url = f"https://www.edickinson.org/editions/1/works/{tei_number}.tei"

    # Set the file name as the TEI number
    file_name = f"{tei_number}.tei"

    # Send a GET request to download the TEI file
    response = requests.get(url)

    # Save the TEI file in the target folder
    with open(target_folder + file_name, 'wb') as file:
        file.write(response.content)

    print(f"Downloaded TEI file {tei_number}.tei")
print("All TEI files downloaded and saved to Google Drive.")